// GitHubへアップロードする際は、このファイル名を vol2.js に変更してください。

window.vol2 = [
{
    vol:2,
    name:"ロンドンドライジントニック",
    glass:"角g",
    recipe:"ビーフィーター47 40cc、ライムJ 5cc、トニック 60cc、ソーダ 15cc",
    garnish:"ライムピール",
    history:"1910年代以降に広まったジントニックの店舗レシピ版。"
},
{
    vol:2,
    name:"オレンジジントニック",
    glass:"12oz",
    recipe:"ビーフィーター40 40cc、トニック 80cc",
    garnish:"1/12オレンジ絞り込み、Lマドラー",
    history:"オレンジの香りを加えたジントニックアレンジ。"
},
{
    vol:2,
    name:"シトラスジントニック",
    glass:"12oz",
    recipe:"ビーフィーター40 40cc、トニック 80cc",
    garnish:"1/16GFフルーツ絞り込み、Lマドラー",
    history:"グレープフルーツを使ったシトラス系アレンジ。"
},
{
    vol:2,
    name:"○○ソーダ",
    glass:"12oz",
    recipe:"ベース40cc、ソーダ80cc",
    garnish:"1/8レモン、Lマドラー",
    history:"ジン・ウォッカ・ラム・テキーラ対応。"
},
{
    vol:2,
    name:"○○トニック",
    glass:"12oz",
    recipe:"ベース40cc、トニック80cc",
    garnish:"1/8ライム、Lマドラー",
    history:"ジン・ウォッカ・ラム・テキーラ対応。"
},
{
    vol:2,
    name:"○○リッキー",
    glass:"12oz",
    recipe:"ベース40cc、ソーダ80cc",
    garnish:"1/8ライム絞り込み、Lマドラー",
    history:"リッキーはライムを使用するのが特徴。"
},
{
    vol:2,
    name:"○○バック",
    glass:"12oz",
    recipe:"ベース40cc、ジンジャー80cc",
    garnish:"1/8レモン絞り込み、Lマドラー",
    history:"バック系はジンジャーエール使用。"
},
{
    vol:2,
    name:"ジンライム",
    glass:"ファッション",
    recipe:"ジン60cc、1/2ライム絞り込み",
    garnish:"Sマドラー、4つ氷",
    history:"シンプルなショートスタイル。"
},
{
    vol:2,
    name:"トムコリンズ",
    glass:"コリンズ",
    recipe:"ジン30cc、レモンJ10cc、パウダーシュガー2tsp、ソーダ55cc",
    garnish:"Lマドラー、レモンスライス、レッドチェリー",
    history:"19世紀アメリカ生まれのクラシックカクテル。"
},
{
    vol:2,
    name:"シンガポールスリング",
    glass:"コリンズ",
    recipe:"ジン30cc、レモンJ15cc、パウダーシュガー1tsp、ソーダ40cc、チェリーブランデー15cc",
    garnish:"Lマドラー、レモンスライス、レッドチェリー",
    history:"1915年にシンガポールのラッフルズ・ホテルで誕生。"
},
{
    vol:2,
    name:"マティーニ",
    glass:"カクテル",
    recipe:"ジン45cc、チンザノドライ15cc",
    garnish:"スタッフドオリーブ、レモンピール",
    history:"カクテルの王様と呼ばれる。"
},
{
    vol:2,
    name:"ギムレット",
    glass:"カクテル",
    recipe:"ジン45cc、ライムJ15cc、パウダーシュガー1tsp",
    garnish:"",
    history:"イギリス海軍が起源とされる。"
},
{
    vol:2,
    name:"ブルームーン",
    glass:"カクテル",
    recipe:"ジン30cc、バイオレット15cc、レモンJ15cc",
    garnish:"",
    history:"スミレの香りが特徴。"
},
{
    vol:2,
    name:"ホワイトレディ",
    glass:"カクテル",
    recipe:"ジン30cc、ホワイトキュラソー15cc、レモンJ15cc",
    garnish:"",
    history:"白い見た目が名前の由来。"
},
{
    vol:2,
    name:"ジンフィズ",
    glass:"コリンズ",
    recipe:"ジン30cc、レモンJ15cc、パウダーシュガー1tsp、ソーダ55cc",
    garnish:"Lマドラー、レモンスライス",
    history:"フィズは泡立つという意味。"
}
];
