// GitHubへアップロードする際は、このファイル名を vol3.js に変更してください。

window.vol3 = [
{
    vol:3,
    name:"モスコミュール",
    glass:"12oz",
    recipe:"ウォッカ40cc、ライムJ5cc、ジンジャーエール80cc",
    garnish:"Lマドラー、1/8ライム絞り込み",
    history:"1940年代アメリカで誕生したウォッカカクテル。"
},
{
    vol:3,
    name:"スクリュードライバー",
    glass:"12oz",
    recipe:"ウォッカ40cc、オレンジジュース80cc",
    garnish:"Lマドラー、1/12オレンジ",
    history:"油田労働者がドライバーで混ぜたという説がある。"
},
{
    vol:3,
    name:"ブルドッグ",
    glass:"12oz",
    recipe:"ウォッカ40cc、グレープフルーツJ80cc",
    garnish:"Lマドラー、1/16グレープフルーツ",
    history:"ウォッカとグレープフルーツの定番。"
},
{
    vol:3,
    name:"ブラッディーメアリー",
    glass:"12oz",
    recipe:"ウォッカ40cc、トマトジュース80cc",
    garnish:"Lマドラー、1/8レモン",
    history:"イングランド女王メアリー1世が名前の由来とされる。"
},
{
    vol:3,
    name:"ソルティドッグ",
    glass:"ソルティドッグ",
    recipe:"ウォッカ40cc、グレープフルーツJ80cc",
    garnish:"スノースタイル",
    history:"グラスの塩が特徴の代表的カクテル。"
},
{
    vol:3,
    name:"ブラックルシアン",
    glass:"ファッション",
    recipe:"ウォッカ30cc、カルーア15cc",
    garnish:"",
    history:"1940年代にベルギーで誕生。"
},
{
    vol:3,
    name:"バラライカ",
    glass:"カクテル",
    recipe:"ウォッカ30cc、ホワイトキュラソー15cc、レモンJ15cc",
    garnish:"",
    history:"ロシアの民族楽器バラライカに由来する。"
}
];
