// GitHubへアップロードする際は、このファイル名を vol4.js に変更してください。

window.vol4 = [
{
    vol:4,
    name:"キューバリブレ",
    glass:"12oz",
    recipe:"ラム40cc、コーラ80cc",
    garnish:"Lマドラー、1/8ライム絞り込み",
    history:"キューバ独立戦争の勝利を祝って誕生したとされる。"
},
{
    vol:4,
    name:"ラムトニック",
    glass:"12oz",
    recipe:"ラム40cc、トニック80cc",
    garnish:"Lマドラー、1/8ライム",
    history:"ラムを使った定番ロングカクテル。"
},
{
    vol:4,
    name:"ラムバック",
    glass:"12oz",
    recipe:"ラム40cc、ジンジャーエール80cc",
    garnish:"Lマドラー、1/8レモン絞り込み",
    history:"バック系はジンジャーエールを使用する。"
},
{
    vol:4,
    name:"テキーラサンライズ",
    glass:"12oz",
    recipe:"テキーラ40cc、オレンジジュース80cc、グレナデン10cc",
    garnish:"Lマドラー、1/12オレンジ",
    history:"日の出をイメージした見た目が名前の由来。"
},
{
    vol:4,
    name:"メキシコーク",
    glass:"12oz",
    recipe:"テキーラ40cc、コーラ80cc",
    garnish:"Lマドラー、1/8ライム絞り込み",
    history:"テキーラベースのコーラカクテル。"
},
{
    vol:4,
    name:"テキーラトニック",
    glass:"12oz",
    recipe:"テキーラ40cc、トニック80cc",
    garnish:"Lマドラー、1/8ライム",
    history:"シンプルで飲みやすいテキーラカクテル。"
},
{
    vol:4,
    name:"マルガリータ",
    glass:"カクテル",
    recipe:"テキーラ30cc、ホワイトキュラソー15cc、レモンJ15cc",
    garnish:"スノースタイル",
    history:"世界的に有名なテキーラベースのショートカクテル。"
}
];
