// GitHubへアップロードする際は、このファイル名を vol6.js に変更してください。

window.vol6 = [
{
    vol:6,
    name:"キール",
    glass:"フルート",
    recipe:"カシス20cc、シャルドネ100cc",
    garnish:"",
    history:"白ワインにカシスを加えるフランス生まれのカクテル。"
},
{
    vol:6,
    name:"キールロワイヤル",
    glass:"フルート",
    recipe:"カシス20cc、コルドンネグロ100cc",
    garnish:"",
    history:"キールをスパークリングワインで作る華やかなアレンジ。"
},
{
    vol:6,
    name:"ミモザ",
    glass:"フルート",
    recipe:"OJ60cc、コルドンネグロ60cc",
    garnish:"",
    history:"黄色い花ミモザに見た目が似ていることが名前の由来。"
},
{
    vol:6,
    name:"ワインクーラー",
    glass:"ワイングラス",
    recipe:"ペシェ20cc、OJ20cc、シャルドネ80cc、グレナデン10cc",
    garnish:"細口ストロー2本、1/12オレンジ、クラッシュアイス",
    history:"フルーティーで飲みやすいワインカクテル。"
},
{
    vol:6,
    name:"アメリカンレモネード",
    glass:"ワイングラス",
    recipe:"レモンJ40cc、パウダーシュガー3tsp、水80cc、カベルネ40cc",
    garnish:"細口ストロー2本、レモンスライス、2個氷",
    history:"赤ワインをフロートさせる見た目が特徴のカクテル。"
}
];
