// GitHubへアップロードする際は、このファイル名を vol7.js に変更してください。

window.vol7 = [
{
    vol:7,
    name:"カシスオレンジ",
    glass:"12oz",
    recipe:"カシス40cc、OJ80cc",
    garnish:"Lマドラー、1/12オレンジ",
    history:"世界中で親しまれている定番カシスカクテル。"
},
{
    vol:7,
    name:"カシスウーロン",
    glass:"12oz",
    recipe:"カシス40cc、ウーロン茶80cc",
    garnish:"Lマドラー",
    history:"甘さを抑えた飲みやすいカシスカクテル。"
},
{
    vol:7,
    name:"パライソグレープフルーツ",
    glass:"12oz",
    recipe:"パライソ40cc、グレープフルーツJ80cc",
    garnish:"Lマドラー、1/16グレープフルーツ",
    history:"パライソのライチの香りとグレープフルーツの相性が良い。"
},
{
    vol:7,
    name:"チャイナブルー",
    glass:"12oz",
    recipe:"パライソ30cc、グレープフルーツJ30cc、トニック50cc、ブルーキュラソー10cc",
    garnish:"Lマドラー、1/16グレープフルーツ",
    history:"日本で人気のライチ系カクテル。"
},
{
    vol:7,
    name:"ファジーネーブル",
    glass:"12oz",
    recipe:"ペシェ40cc、OJ80cc",
    garnish:"Lマドラー、1/12オレンジ",
    history:"桃の甘味が特徴の定番カクテル。"
},
{
    vol:7,
    name:"スプモーニ",
    glass:"12oz",
    recipe:"カンパリ30cc、グレープフルーツJ30cc、トニック60cc",
    garnish:"Lマドラー、1/16グレープフルーツ",
    history:"イタリア生まれのビター系カクテル。"
},
{
    vol:7,
    name:"ヨーグリートパイン",
    glass:"10oz",
    recipe:"ヨーグリート30cc、パインJ70cc",
    garnish:"レモンスライス",
    history:"ヨーグルトリキュールの爽やかなカクテル。"
},
{
    vol:7,
    name:"照葉樹林",
    glass:"コリンズ",
    recipe:"グリーンティー30cc、ウーロン茶70cc",
    garnish:"Lマドラー",
    history:"緑と茶色の見た目が照葉樹林を連想させる。"
},
{
    vol:7,
    name:"カルアミルク",
    glass:"ファッション",
    recipe:"カルーア30cc、牛乳70cc",
    garnish:"Sマドラー",
    history:"コーヒーリキュールを使った定番デザートカクテル。"
},
{
    vol:7,
    name:"マリブパイン",
    glass:"10oz",
    recipe:"マリブ30cc、パインJ70cc",
    garnish:"レモンスライス",
    history:"ココナッツの香りが特徴。"
},
{
    vol:7,
    name:"アプリコットクーラー",
    glass:"コリンズ",
    recipe:"アプリコットブランデー30cc、レモンJ15cc、グレナデン10cc、ソーダ45cc",
    garnish:"Lマドラー、レモンスライス、レッドチェリー",
    history:"甘酸っぱい味わいのロングカクテル。"
}
];
