// GitHubへアップロードする際は、このファイル名を vol8.js に変更してください。
// 資料画像 Vol.8（ビア・ソフト）準拠版

window.vol8 = [
{
    vol:8,
    name:"シャンディーガフ",
    glass:"小ピルスナー",
    recipe:"ジンジャーエール150cc、ドラフト150cc",
    garnish:"",
    history:"ビールとジンジャーエールを合わせる代表的なビアカクテル。"
},
{
    vol:8,
    name:"レッドアイ",
    glass:"小ピルスナー",
    recipe:"トマトジュース150cc、ドラフト150cc",
    garnish:"",
    history:"ビールとトマトジュースを合わせる定番のビアカクテル。"
},
{
    vol:8,
    name:"オレンジジュース",
    glass:"10oz",
    recipe:"100cc",
    garnish:"",
    history:"店舗ソフトドリンクメニュー。"
},
{
    vol:8,
    name:"グレープフルーツJ",
    glass:"10oz",
    recipe:"100cc",
    garnish:"",
    history:"店舗ソフトドリンクメニュー。"
},
{
    vol:8,
    name:"クランベリージュース",
    glass:"10oz",
    recipe:"100cc",
    garnish:"",
    history:"店舗ソフトドリンクメニュー。"
},
{
    vol:8,
    name:"パイナップルジュース",
    glass:"10oz",
    recipe:"100cc",
    garnish:"",
    history:"店舗ソフトドリンクメニュー。"
},
{
    vol:8,
    name:"ウーロン茶",
    glass:"10oz",
    recipe:"100cc",
    garnish:"",
    history:"店舗ソフトドリンクメニュー。"
},
{
    vol:8,
    name:"トマトジュース",
    glass:"10oz",
    recipe:"100cc",
    garnish:"",
    history:"店舗ソフトドリンクメニュー。"
},
{
    vol:8,
    name:"ジンジャーエール",
    glass:"10oz",
    recipe:"100cc",
    garnish:"",
    history:"店舗ソフトドリンクメニュー。"
},
{
    vol:8,
    name:"ペプシコーラ",
    glass:"10oz",
    recipe:"100cc",
    garnish:"",
    history:"店舗ソフトドリンクメニュー。"
}
];
